### ISSUE TITLE
Navigation section and vignettes 

### ISSUE THREAD

**Issue by vnminin** [igoldsteinh/ww_paper#1]
I am not sure I understood how to proceed to reproduce paper results. Can we use quarto or RMarkdown to create a small number of vignettes? I am trying to put myself in the shoes of a PhD student who is trying to understand our paper and want to start by reproducing results of the paper.

**Comment by igoldsteinh** [comment]
I think this is inevitably going to be a little awkward because we're using multiple languages, but sure, I'll try to cook up something

**Comment by igoldsteinh** [comment]
What do you think? It seems a lot better to me.

**Comment by vnminin** [comment]
Definitely better, Isaac, but not very accessible to anyone new to Julia yet.

In the model fitting workflow, lets' provide stet-by-step instructions: 1) go to the root directory, start julia by typing julia in the terminal, run "import Pkg", run "Pkg.instantiate()" or run "julia --project=. scripts/fit_models/fit_eirr.jl" 

I was trying to follow your guidelines, but still got nowhere... Could be me not knowing what I am doing with Julia, but I suspect our reviewers and readers will have similar issues

**Comment by igoldsteinh** [comment]
Can you be more specific about "getting nowhere"? Where did you get stuck?

**Comment by vnminin** [comment]
instantiate in REPL didn't load required packages for the project, when I started REPL, but then if it did, I would not know how to run the scripts. 

There is a lot of passive voice in the sentences below and not a lot of concrete directions about how to run these scripts, where to expect the output to appear, what assumptions theses scripts are making, etc.

> As an example, to generate results from the the EIRR-ww model, fit_eirrc_closed.jl is used to fit the model, then eirrc_closed_generate_pp_and_gq.jl to re-scale the posterior and generate posterior predictive values, finally process_results_eirrc_closed.R creates tidy versions of the posterior and posterior predictive summaries. When summarising results from multiple simulations, summarise_eirrc_closed.R creates summary outputs. Similarly named files exist for all models used in the paper.
